export var PostcardsData = [
  {
    id: "1",
    images: ["postcard1.jpg"],
    title: "Scenic Mountain View",
    price: 4.99,
    quantity: 100,
    placeId: "1",
  },
  {
    id: "2",
    images: ["postcard2.jpg", "postcard1.jpg"],
    title: "Historic Landmark",
    price: 3.49,
    quantity: 75,
    placeId: "1",
  },
  {
    id: "3",
    images: ["postcard3.jpg", "postcard1.jpg"],
    title: "City Skyline",
    price: 2.99,
    quantity: 50,
    placeId: "6",
  },
  {
    id: "4",
    images: ["postcard4.jpg", "postcard1.jpg", "postcard3.jpg"],
    title: "Beach Sunset",
    price: 5.99,
    quantity: 120,
    placeId: "2",
  },
  {
    id: "5",
    images: ["postcard5.jpg"],
    title: "Floral Garden",
    price: 3.99,
    quantity: 90,
    placeId: "2",
  },
  {
    id: "6",
    images: ["postcard6.jpg"],
    title: "Vintage Car Collection",
    price: 6.49,
    quantity: 60,
    placeId: "3",
  },
  {
    id: "7",
    images: ["postcard7.jpg"],
    title: "Coastal Lighthouse",
    price: 4.29,
    quantity: 85,
    placeId: "4",
  },
  {
    id: "8",
    images: ["postcard8.jpg"],
    title: "Wildlife Safari",
    price: 7.99,
    quantity: 110,
    placeId: "5",
  },
  {
    id: "9",
    images: ["postcard9.jpg"],
    title: "Urban Street Art",
    price: 4.79,
    quantity: 70,
    placeId: "6",
  },
  {
    id: "10",
    images: ["postcard10.jpg"],
    title: "Countryside Landscape",
    price: 5.49,
    quantity: 95,
    placeId: "6",
  },
]

export let PlacesData = [
  {
    id: "1",
    location: "New York City",
    isVisited: true,
  },
  {
    id: "2",
    location: "Paris",
    isVisited: false,
  },
  {
    id: "3",
    location: "Tokyo",
    isVisited: true,
  },
  {
    id: "4",
    location: "London",
    isVisited: true,
  },
  {
    id: "5",
    location: "Rome",
    isVisited: false,
  },
  {
    id: "6",
    location: "Sydney",
    isVisited: true,
  },
]
